In [1]:
from automaticTB.SALCs import VectorSpace, decompose_vectorspace_to_namedLC
from automaticTB.interaction import InteractionEquation
from automaticTB.examples.structures import get_AH3_nncluster
from automaticTB.printing import print_ao_pairs

print("Solving for AH3 molecular ...")
nncluster = get_AH3_nncluster()
vectorspace = VectorSpace.from_NNCluster(nncluster)
named_lcs = decompose_vectorspace_to_namedLC(vectorspace, nncluster.sitesymmetrygroup)

print("Symmetry adopted Linear combinations ...")
for nlc in named_lcs:
    print(nlc.name)
    print(nlc.lc)
    
free_pairs = InteractionEquation.from_nncluster_namedLC(nncluster, named_lcs).free_AOpairs
print_ao_pairs(nncluster, free_pairs)

Solving for AH3 molecular ...
Symmetry adopted Linear combinations ...
A_''_2 @ 1^th A_''_2
└─  C @ (  0.00,  0.00,  0.00) :: +1.000(0 1 0)
A_'_1 @ 1^th A_'_1
└─  C @ (  0.00,  0.00,  0.00) :: +1.000(0 0 0)
A_'_1 @ 2^th A_'_1
├─  H @ (  0.00,  2.00,  0.00) :: +0.577(0 0 0)
├─  H @ (  1.73, -1.00,  0.00) :: +0.577(0 0 0)
└─  H @ ( -1.73, -1.00,  0.00) :: +0.577(0 0 0)
E_'->A_1 @ 1^th E_'
└─  C @ (  0.00,  0.00,  0.00) :: +0.500(0 1-1)+0.866(0 1 1)
E_'->B_2 @ 1^th E_'
└─  C @ (  0.00,  0.00,  0.00) :: -0.866(0 1-1)+0.500(0 1 1)
E_'->A_1 @ 2^th E_'
├─  H @ (  0.00,  2.00,  0.00) :: +0.408(0 0 0)
├─  H @ (  1.73, -1.00,  0.00) :: +0.408(0 0 0)
└─  H @ ( -1.73, -1.00,  0.00) :: -0.816(0 0 0)
E_'->B_2 @ 2^th E_'
├─  H @ (  0.00,  2.00,  0.00) :: -0.707(0 0 0)
└─  H @ (  1.73, -1.00,  0.00) :: +0.707(0 0 0)
Free interaction parameters: 
  1 > Free AO interaction: C 0s -> C 0s @ (  0.00,  0.00,  0.00)
  2 > Free AO interaction: C 0s -> H 0s @ ( -1.73, -1.00,  0.00)
  3 > Free AO interaction: C

In [2]:
import numpy as np
# Hamiltonian matrix in MO basis:
Hij = np.zeros((7,7))
MOlist = [
        "s", # A_'_1 @ 1^th A_'_1
        "px", # E_'->A_1 @ 1^th E_'
        "py", # E_'->B_2 @ 1^th E_'
        "pz", # A_''_2 @ 1^th A_''_2
        "s_s", # A_'_1 @ 2^th A_'_1
        "s_px", # E_'->A_1 @ 2^th E_'
        "s_py" # E_'->B_2 @ 2^th E_'
    ]

interactions = {
        "s s": -25,
        "px px": -13,
        "py py": -13,
        "pz pz": -13,
        "s_s s_s": -14,
        "s_px s_px": -12,
        "s_py s_py": -12,
        "s s_s": 3.0,
        "s_s s": 3.0,
        "px s_px": 4.0,
        "s_px px": 4.0,
        "py s_py": 4.0,
        "s_py py": 4.0
    }

for i,mo1 in enumerate(MOlist):
    for j,mo2 in enumerate(MOlist):
        Hij[i,j] = interactions.setdefault(" ".join([mo1,mo2]),0)

print("The Molecular Hamiltonian in MO basis is:")
print(Hij)
w, v = np.linalg.eig(Hij)
print()
print("Solved eigenvalues are:")

start = 0
sortedW = sorted(w)
while start + 3 <= len(w):
    print(f"{sortedW[start]:>8.2f}{sortedW[start+1]:>8.2f}{sortedW[start+2]:>8.2f}")
    start += 3
    

The Molecular Hamiltonian in MO basis is:
[[-25.   0.   0.   0.   3.   0.   0.]
 [  0. -13.   0.   0.   0.   4.   0.]
 [  0.   0. -13.   0.   0.   0.   4.]
 [  0.   0.   0. -13.   0.   0.   0.]
 [  3.   0.   0.   0. -14.   0.   0.]
 [  0.   4.   0.   0.   0. -12.   0.]
 [  0.   0.   4.   0.   0.   0. -12.]]

Solved eigenvalues are:
  -25.76  -16.53  -16.53
  -13.24  -13.00   -8.47


In [3]:
from automaticTB.plotting import DensityCubePlot

print("Plot Symmetry adopted Linear Combinations")
for nlc in named_lcs:
    plot = DensityCubePlot.from_linearcombinations([nlc.lc], quality="high")
    plot.plot_to_file(f"{str(nlc.name)}.cube")

TypeError: type object argument after * must be an iterable, not int